CREATE TABLE IF NOT EXISTS public.ekk_device (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id integer NOT NULL,
    serial_number character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    brand character varying(255) NOT NULL,
    model character varying(255) NOT NULL,
    status integer NOT NULL DEFAULT 1,
    uuid_id uuid NOT NULL DEFAULT gen_random_uuid(),
    modbus_host inet NOT NULL,
    modbus_port integer NOT NULL DEFAULT 502,
    modbus_unit_id integer NOT NULL DEFAULT 1,
    web_base_url text,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ekk_device_site_id UNIQUE (site_id),
    CONSTRAINT uq_ekk_device_serial_number UNIQUE (serial_number)
);

CREATE INDEX IF NOT EXISTS idx_ekk_device_status ON public.ekk_device (status);

CREATE TABLE IF NOT EXISTS public.ekk_device_register_map (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ekk_device_id integer NOT NULL,
    quantity character varying(255) NOT NULL,
    modbus_register integer NOT NULL,
    number_of_modbus_registers integer NOT NULL,
    modbus_data_type character varying(32) NOT NULL,
    modbus_units character varying(64),
    web_page_tag character varying(255),
    scale_multiplier numeric(18,6) NOT NULL DEFAULT 1,
    is_enabled boolean NOT NULL DEFAULT true,
    display_order integer NOT NULL DEFAULT 0,
    notes text,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ekk_device_register_map_device
        FOREIGN KEY (ekk_device_id) REFERENCES public.ekk_device(id) ON DELETE CASCADE,
    CONSTRAINT uq_ekk_device_register_map_quantity UNIQUE (ekk_device_id, quantity),
    CONSTRAINT uq_ekk_device_register_map_register UNIQUE (ekk_device_id, modbus_register)
);

CREATE INDEX IF NOT EXISTS idx_ekk_device_register_map_device
    ON public.ekk_device_register_map (ekk_device_id, is_enabled, modbus_register);

CREATE TABLE IF NOT EXISTS public.ekk_device_reading (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ekk_device_id integer NOT NULL,
    site_id integer NOT NULL,
    logtime timestamp without time zone NOT NULL,
    poll_started_at timestamp without time zone NOT NULL,
    poll_finished_at timestamp without time zone,
    status character varying(32) NOT NULL DEFAULT 'SUCCESS',
    raw_payload jsonb,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ekk_device_reading_device
        FOREIGN KEY (ekk_device_id) REFERENCES public.ekk_device(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ekk_device_reading_lookup
    ON public.ekk_device_reading (site_id, ekk_device_id, logtime DESC);

CREATE TABLE IF NOT EXISTS public.ekk_device_reading_value (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reading_id bigint NOT NULL,
    register_map_id integer NOT NULL,
    quantity character varying(255) NOT NULL,
    modbus_register integer NOT NULL,
    value_numeric numeric(20,6),
    value_text text,
    value_json jsonb,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ekk_device_reading_value_reading
        FOREIGN KEY (reading_id) REFERENCES public.ekk_device_reading(id) ON DELETE CASCADE,
    CONSTRAINT fk_ekk_device_reading_value_register_map
        FOREIGN KEY (register_map_id) REFERENCES public.ekk_device_register_map(id) ON DELETE CASCADE,
    CONSTRAINT uq_ekk_device_reading_value UNIQUE (reading_id, register_map_id)
);

CREATE INDEX IF NOT EXISTS idx_ekk_device_reading_value_quantity
    ON public.ekk_device_reading_value (quantity, created_at DESC);

CREATE TABLE IF NOT EXISTS public.ekk_device_poll_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ekk_device_id integer,
    site_id integer NOT NULL,
    poll_started_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    poll_finished_at timestamp without time zone,
    level character varying(16) NOT NULL,
    status character varying(32) NOT NULL,
    message text NOT NULL,
    error_detail text,
    traceback text,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ekk_device_poll_log_device
        FOREIGN KEY (ekk_device_id) REFERENCES public.ekk_device(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_ekk_device_poll_log_site_created
    ON public.ekk_device_poll_log (site_id, created_at DESC);
